---
- name: Autoremove unused packages
  become: true
  ansible.builtin.apt:
    autoremove: true
  register: apt_autoremove_result

- name: Autoremove output details
  ansible.builtin.debug:
    var: apt_autoremove_result
